//
//  Frankl.swift
//  Daily quotes
//
//  Created by Abhijot Kaler on 09/09/20.
//  Copyright © 2020 KalerCorp. All rights reserved.
//

import Foundation

struct Frankl{
    var quotes : [String] = [
    "The truth is that as the struggle for survival has subsided, the question has emerged: survival for what? Even more people today have the means to live but no meaning to live for. (The Unheard Cry for Meaning)",
    "The existential vacuum is a widespread phenomenon of the 20th century. This is understandable; it may be due to a twofold loss which man has had to undergo since he became a truly human being. At the beginning of human history, man lost some of the basic animal instincts in which an animal’s behavior is imbedded and by which it is secured. . .In addition to this, however, man has suffered another loss in his more recent development inasmuch as the traditions which buttressed his behavior are now rapidly diminishing. No instinct tells him what he has to do, and no tradition tells him what he ought to do; sometimes he does not even know what he wishes to do. Instead, he either wishes to do what other people do (conformism) or he does what other people wish him to do (totalitarianism). (Man’s Search for Meaning)",
    "This ultimate meaning necessarily exceeds and surpasses the finite intellectual capacities of man…What is demanded of man is not, as some existential philosophers teach, to endure the meaninglessness of life, but rather to bear his incapacity to grasp its unconditional meaningfulness in rational terms. (Man’s Search for Meaning)",
    "We [need] to stop asking about the meaning of life, and instead to think of ourselves as those who [are] being questioned by life – daily and hourly. Our answer must consist, not in talk and meditation, but in right action and right conduct. Life ultimately means the responsibility to find the right answers to its problems and to fulfill the tasks which it constantly sets for each individual. (Man’s Search for Meaning)",
    "To put the question [of the meaning of life] in general terms would be comparable to the question posed to a chess champion: “Tell me, master, what is the best move in the world?” There simply is no such thing as the best or even a good move apart from a particular situation in a game and the particular personality of one’s opponent. The same holds for human existence. One should not search for an abstract meaning of life. Everyone has his own specific vocation or mission in life to carry out a concrete assignment which demands fulfillment. (Man’s Search for Meaning)",
    "We must never forget that we may also find meaning in life even when confronted with a hopeless situation, when facing a fate that cannot be changed. For what then matters is to bear witness to the uniquely human potential at its best, which is to transform a personal tragedy into a triumph, to turn one’s predicament into a human achievement. When we are no longer able to change a situation. . .we are challenged to change ourselves. (Man's Search for Meaning)",
    "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances, to choose one’s own way. (Man's Search for Meaning)",
    "Don't aim at success. The more you aim at it and make it a target, the more you are going to miss it. For success, like happiness, cannot be pursued; it must ensue, and it only does so as the unintended side effect of one's personal dedication to a cause greater than oneself or as the by-product of one's surrender to a person other than oneself. Happiness must happen, and the same holds for success: you have to let it happen by not caring about it. I want you to listen to what your conscience commands you to do and go on to carry it out to the best of your knowledge. Then you will live to see that in the long-run—in the long-run, I say!—success will follow you precisely because you had forgotten to think about it. (Man's Search for Meaning)",
    "Those who have a 'why' to live, can bear with almost any 'how'. (Man's Search for Meaning)",
    "But there was no need to be ashamed of tears, for tears bore witness that a man had the greatest of courage, the courage to suffer. (Man's Search for Meaning)",
    "Love is the only way to grasp another human being in the innermost core of his personality. No one can become fully aware of the very essence of another human being unless he loves him. By his love he is enabled to see the essential traits and features in the beloved person; and even more, he sees that which is potential in him, which is not yet actualized but yet ought to be actualized. Furthermore, by his love, the loving person enables the beloved person to actualize these potentialities. By making him aware of what he can be and of what he should become, he makes these potentialities come true. (Man's Search for Meaning)",
    "Ultimately, man should not ask what the meaning of his life is, but rather must recognize that it is he who is asked. In a word, each man is questioned by life; and he can only answer to life by answering for his own life; to life he can only respond by being responsible. (Man's Search for Meaning)",
    "In some ways suffering ceases to be suffering at the moment it finds a meaning, such as the meaning of a sacrifice. (Man's Search for Meaning)",
    "So live as if you were living already for the second time and as if you had acted the first time as wrongly as you are about to act now! (Man's Search for Meaning)",
    "What is to give light must endure burning. (Man's Search for Meaning)",
    "No man should judge unless he asks himself in absolute honesty whether in a similar situation he might not have done the same. (Man's Search for Meaning)",
    "For the first time in my life I saw the truth as it is set into song by so many poets, proclaimed as the final wisdom by so many thinkers. The truth - that Love is the ultimate and highest goal to which man can aspire. Then I grasped the meaning of the greatest secret that human poetry and human thought and belief have to impart: The salvation of man is through love and in love. (Man's Search for Meaning)",
    "The one thing you can’t take away from me is the way I choose to respond to what you do to me. The last of one’s freedoms is to choose one’s attitude in any given circumstance.",
    "It did not really matter what we expected from life, but rather what life expected from us. We needed to stop asking about the meaning of life, and instead to think of ourselves as those who were being questioned by life—daily and hourly. Our answer must consist, not in talk and meditation, but in right action and in right conduct. Life ultimately means taking the responsibility to find the right answer to its problems and to fulfill the tasks which it constantly sets for each individual. (Man's Search for Meaning)",
    "Life is never made unbearable by circumstances, but only by lack of meaning and purpose. (Man's Search for Meaning)",
    "The pessimist resembles a man who observes with fear and sadness that his wall calendar, from which he daily tears a sheet, grows thinner with each passing day. On the other hand, the person who attacks the problems of life actively is like a man who removes each successive leaf from his calendar and files it neatly and carefully away with its predecessors, after first having jotted down a few diary notes on the back. He can reflect with pride and joy on all the richness set down in these notes, on all the life he has already lived to the fullest. What will it matter to him if he notices that he is growing old? Has he any reason to envy the young people whom he sees, or wax nostalgic over his own lost youth? What reasons has he to envy a young person? For the possibilities that a young person has, the future which is in store for him?\nNo, thank you,' he will think. 'Instead of possibilities, I have realities in my past, not only the reality of work done and of love loved, but of sufferings bravely suffered. These sufferings are even the things of which I am most proud, although these are things which cannot inspire envy.(Man's Search for Meaning)",
    "If there is meaning in life at all, then there must be meaning in suffering. (Man's Search for Meaning)",
    "Forces beyond your control can take away everything you possess except one thing, your freedom to choose how you will respond to the situation.",
    "To draw an analogy: a man's suffering is similar to the behavior of a gas. If a certain quantity of gas is pumped into an empty chamber, it will fill the chamber completely and evenly, no matter how big the chamber. Thus suffering completely fills the human soul and conscious mind, no matter whether the suffering is great or little. Therefore the 'size' of human suffering is absolutely relative. (Man's Search for Meaning)",
    "We who lived in concentration camps can remember the men who walked through the huts comforting others, giving away their last piece of bread. They may have been few in number, but they offer sufficient proof that everything can be taken from a man but one thing: the last of the human freedoms -- to choose one's attitude in any given set of circumstances, to choose one's own way.",
    "By declaring that man is responsible and must actualize the potential meaning of his life, I wish to stress that the true meaning of life is to be discovered in the world rather than within man or his own psyche, as though it were a closed system. I have termed this constitutive characteristic 'the self-transcendence of human existence.' It denotes the fact that being human always points, and is directed, to something or someone, other than oneself--be it a meaning to fulfill or another human being to encounter. The more one forgets himself--by giving himself to a cause to serve or another person to love--the more human he is and the more he actualizes himself. What is called self-actualization is not an attainable aim at all, for the simple reason that the more one would strive for it, the more he would miss it. In other words, self-actualization is possible only as a side-effect of self-transcendence. (Man's Search for Meaning)",
    "Man does not simply exist but always decides what his existence will be, what he will become the next moment. By the same token, every human being has the freedom to change at any instant. (Man's Search for Meaning)",
    "A human being is not one thing among others; things determine each other, but man is ultimately self-determining. What he becomes - within the limits of endowment and environment- he has made out of himself. In the concentration camps, for example, in this living laboratory and on this testing ground, we watched and witnessed some of our comrades behave like swine while others behaved like saints. Man has both potentialities within himself; which one is actualized depends on decisions but not on conditions. (Man's Search for Meaning)",
    "Dostoevski said once, 'There is only one thing I dread: not to be worthy of my sufferings.' These words frequently came to my mind after I became acquainted with those martyrs whose behavior in camp, whose suffering and death, bore witness to the fact that the last inner freedom cannot be lost. It can be said that they were worthy of the their sufferings; the way they bore their suffering was a genuine inner achievement. It is this spiritual freedom—which cannot be taken away—that makes life meaningful and purposeful.(Man's Search for Meaning)",
    "The attempt to develop a sense of humor and to see things in a humorous light is some kind of a trick learned while mastering the art of living. (Man's Search for Meaning)",
    ]
    
}
