//
//  Jung.swift
//  Daily quotes
//
//  Created by Abhijot Kaler on 12/09/20.
//  Copyright © 2020 KalerCorp. All rights reserved.
//

import Foundation

struct Jung{
    let quotes: [String] =
    [
    "This confrontation is the first test of courage on the inner way, a test sufficient to frighten off most people, for the meeting with ourselves belongs to the more unpleasant things that can be avoided so long as we can project everything negative into the environment. But if we are able to see our own shadow and can bear knowing about it, then a small part of the problem has already been solved: we have at least brought up the personal unconscious. The shadow is a living part of the personality and therefore wants to live with it in some form. It cannot be argued out of existence or rationalized into harmlessness. This problem is exceedingly difficult, because it not only challenges the whole man, but reminds him at the same time of his helplessness and ineffectuality.",

    "Tears, sorrow, and disappointment are bitter, but wisdom is the comforter in all psychic suffering. Indeed, bitterness and wisdom form a pair of alternatives: where there is bitterness wisdom is lacking, and where wisdom is there can be no bitterness.",

    "The creation of something new is not accomplished by the intellect but by the play instinct acting from inner necessity. The creative mind plays with the objects it loves.",
    "In the last analysis, the essential thing is the life of individual. This alone makes history, here alone do the great transformations take place, and the whole future, the whole history of the world, ultimately springs as a gigantic summation from these hidden source in individuals.",
    "But, if you have nothing at all to create, then perhaps you create yourself.",
    "A creative person has little power over his own life. He is not free. He is captive and driven by his daimon.",
    "Your visions will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes.",
    "Until you make the unconscious conscious, it will direct your life and you will call it fate.",
    "The dream is the small hidden door in the deepest and most intimate sanctum of the soul, which opens into that primeval cosmic night that was soul long before there was a conscious ego and will be soul far beyond what a conscious ego could ever reach.",
    "It is often tragic to see how blatantly a man bungles his own life and the lives of others yet remains totally incapable of seeing how much the whole tragedy originates in himself, and how he continually feeds it and keeps it going.",
    "There is no coming to consciousness without pain. People will do anything, no matter how absurd, in order to avoid facing their own Soul. One does not become enlightened by imagining figures of light, but by making the darkness conscious.",
    "The decisive question for man is: Is he related to something infinite or not? That is the telling question of his life. Only if we know that the thing which truly matters is the infinite can we avoid fixing our interests upon futilities, and upon all kinds of goals which are not of real importance. Thus we demand that the world grant us recognition for qualities which we regard as personal possessions: our talent or our beauty. The more a man lays stress on false possessions, and the less sensitivity he has for what is essential, the less satisfying is his life. He feels limited because he has limited aims, and the result is envy and jealousy. If we understand and feel that here in this life we already have a link with the infinite, desires and attitudes change.",
    "Unfortunately there can be no doubt that man is, on the whole, less good than he imagines himself or wants to be. Everyone carries a Shadow, and the less it is embodied in the individual’s conscious life, the blacker and denser it is. If an inferiority is conscious, one always has a chance to correct it. Furthermore, it is constantly in contact with other interests, so that it is continually subjected to modifications. But if it is repressed and isolated from consciousness, it never gets corrected and is liable to burst forth suddenly in a moment of unawareness. At all events, it forms an unconscious snag, thwarting our most well-meant intentions.",
    "Even a happy life cannot be without a measure of darkness, and the word happy would lose its meaning if it were not balanced by sadness. It is far better take things as they come along with patience and equanimity.",

    "The situation which is more common and more familiar to the average man is that in which the ego identifies itself with the ethical values. The identification takes place by means of an identification of the ego with the persona. The ego confuses itself with the façade personality (which is of course in reality only that part of the personality that is tailored to fit the collective), and forgets that it possesses aspects which run counter to the persona. This means that the ego has repressed the shadow side and lost touch with the dark contents, which are negative and for this reason split off from the conscious sector. (A Psychological Approach to the Dogma of the Trinity, Carl Jung)",

    "The enlargement of the light side of consciousness has the necessary consequence that the part of the psyche which is less light and less capable of consciousness is thrown into darkness to such an extent that sooner or later a rift occurs in the psychic system. At first, this is not recognised as such and is therefore projected – i.e. it appears as a religious projection, in the form of a split between the powers of Light and Darkness. (The Symbolism of the Spirit, Carl Jung)",
    "Everyone carries a shadow, and the less it is embodied in the individual’s conscious life, the blacker and denser it is. At all counts, it forms an unconscious snag, thwarting our most well-meant intentions.",
    "Closer examination of the dark characteristics – that is, the inferiorities constituting the shadow – reveals that they have an emotional nature, a kind of autonomy, and accordingly an obsessive or, better, possessive quality.",

    "…this integration [of the shadow] cannot take place and be put to a useful purpose unless one can admit the tendencies bound up with the shadow and allow them some measure of realization – tempered, of course, with the necessary criticism. This leads to disobedience and self disgust, but also to self- reliance, without which individuation is unthinkable.",

    "In myths the hero is the one who conquers the dragon, not the one who is devoured by it. And yet both have to deal with the same dragon. Also, he is no hero who never met the dragon, or who, if once he saw it, declared afterwards that he saw nothing. Equally, only one who has risked the fight with the dragon and is not overcome by it wins the hoard, the “treasure hard to attain”. He alone has a genuine claim to self-confidence, for he has faced the dark ground of his self and thereby has gained himself. This experience gives some faith and trust, the pistis in the ability of the self to sustain him, for everything that menaced him from inside he has made his own. He has acquired the right to believe that he will be able to overcome all future threats by the same means. He has arrived at an inner certainty which makes him capable of self-reliance.",
    "Dreams are impartial, spontaneous products of the unconscious psyche, outside the control of the will. They are pure nature; they show us the unvarnished, natural truth, and are therefore fitted, as nothing else is, to give us back an attitude that accords with our basic human nature when our consciousness has strayed too far from its foundations and run into an impasse.",
    "Fundamentally the persona is nothing real: it is a compromise between the individual and society as to what a man should appear to be. He takes a name, earns a title, represents an office, he is this or that. In a certain sense all this is real, yet in relation to the essential individuality of the person concerned it is only a secondary reality, a product of compromise, in making which others often have a greater share than he. The persona is a semblance, a two-dimensional reality.",
    "The shadow, when it is realized, is the source of renewal; the new and productive impulse cannot come from established values of the ego. When there is an impasse, and sterile time in our lives. . .we must look to the dark, hitherto unacceptable side which has been at our conscious disposal.",
    "The natural function of the animus (as well as of in the anima) is to remain in place between individual consciousness and the collective unconscious; exactly as the persona is a sort of stratum between the ego-consciousness and the objects of the external world. The animus and the anima should function as a bridge, or a door, leading to the images of the collective unconscious, as the persona should be a sort of bridge into the world.",
    "the more numerous and more significant the unconscious contents which are assimilated to the ego, the closer the approximation of the ego to the Self, even though this approximation must be a never-ending process.",
    "…in so far as society is itself composed of de-individualized human beings, it is completely at the mercy of ruthless individualists. Let it band together into groups and organizations as much as it likes – it is just this banding together and the resultant extinction of the individual personality that makes it succumb so readily to a dictator. A million zeros joined together do not, unfortunately, add up to one.",
    "The psychological rule says that when an inner situation is not made conscious, it happens outside as fate. That is to say, when the individual remains undivided and does not become conscious of his inner opposite, the world must perforce act out the conflict and be torn into opposing halves.",
    "The meeting with oneself is, at first, the meeting with one’s own shadow. The shadow is a tight passage, a narrow door, whose painful constriction no one is spared who goes down to the deep well. But one must learn to know oneself in order to know who one is.",
    "There is no generally effective technique for assimilating the shadow. It is more like diplomacy or statesmanship and it is always an individual matter. First one has to accept and take seriously the existence of the shadow. Second, one has to become aware of its qualities and intentions. This happens through conscientious attention to moods, fantasies and impulses. Third, a long process of negotiation is unavoidable.",
    "To find out what is truly individual in ourselves, profound reflection is needed; and suddenly we realize how uncommonly difficult the discovery of individuality is.",
    ]
}
