//
//  Kierkegaard.swift
//  Daily quotes
//
//  Created by Abhijot Kaler on 09/09/20.
//  Copyright © 2020 KalerCorp. All rights reserved.
//

import Foundation

struct Kierkegaard{
    var quotes: [String] = [
    "Life can only be understood backwards; but it must be lived forwards.",
    "What I really lack is to be clear in my mind what I am to do, not what I must know…What matters is to find a purpose…to find a truth that is true for me, to find the idea for which I am willing to live and die…This is what my soul thirsts for as the African desert thirsts for water",
    "Anxiety is the dizziness of freedom.",
    "Most men are subjective toward themselves and objective toward all others, frightfully objective sometimes – but the task is precisely to be objective toward oneself and subjective toward all others.",
    "The despairing man who is unconscious of being in despair is, in comparison with him who is conscious of it, merely a negative step further from the truth and from salvation....unawareness is so far from removing despair, that, on the contrary, it may be the most dangerous form of despair. By unconsciousness the despairing man is in a way secured (but to his own destruction) against becoming aware - that is, he is securely in the power of despair",
    "The greatest hazard of all, losing one’s self, can occur very quietly in the world, as if it were nothing at all. No other loss can occur so quietly; any other loss - an arm, a leg, five dollars, a wife, etc. - is sure to be noticed.",
    "The most painful state of being is remembering the future, particularly the one you'll never have.",
    "The Bible is very easy to understand. But we Christians are a bunch of scheming swindlers. We pretend to be unable to understand it because we know very well that the minute we understand, we are obliged to act accordingly.",
    "Love is the expression of the one who loves, not of the one who is loved. Those who think they can love only the people they prefer do not love at all. Love discovers truths about individuals that others cannot see",
    "No, an illusion can never be destroyed directly, and only by indirect means can it be radically removed..That is, one must approach from behind the person who is under an illusion.",
    "If I were to wish for anything, I should not wish for wealth and power, but for the passionate sense of the potential, for the eye which, ever young and ardent, sees the possible. Pleasure disappoints, possibility never. And what wine is so sparkling, what so fragrant, what so intoxicating, as possibility!",
    "To dare is to lose one's footing momentarily. Not to dare is to lose oneself.",
    "The tyrant dies and his rule is over, the martyr dies and his rule begins.",
    "To venture causes anxiety, but not to venture is to lose one's self.... And to venture in the highest is precisely to be conscious of one's self.",
    "joy and refreshment in contemplating the great men who have found that precious stone for which they sell all, even their lives…proceeding on their chosen course without vacillating…absorbed in themselves and in working toward their higher goal",
    "To stop a man on the street and stand still while talking to him, is not so difficult as to say something to a passer-by in passing, without standing still and without delaying the other, without attempting to persuade him to go the same way, but giving him instead an impulse to go precisely his own way. Such is the relation between one existing individual and another, when the communication concerns the truth as existential inwardness.",
    "An individual in despair despairs over something. So it seems for a moment, but only for a moment; in the same moment the true despair or despair in its true form shows itself. In despairing over something, he really despaired over himself, and now he wants to get rid of himself. For example, when the ambitious man whose slogan is “Either Caesar or nothing” does not get to be Caesar, he despairs over it. But this also means something else: precisely because he did not get to be Caesar, he now cannot bear to be himself. Consequently he does not despair because he did not get to be Caesar but despairs over himself because he did not get to be Caesar.",
    "The proud person always wants to do the right thing, the great thing. But because he wants to do it in his own strength, he is fighting not with man, but with God.",
    "Above all, do not lose your desire to walk. Everyday, I walk myself into a state of well-being & walk away from every illness. I have walked myself into my best thoughts, and I know of no thought so burdensome that one cannot walk away from it. But by sitting still, & the more one sits still, the closer one comes to feeling ill. Thus if one just keeps on walking, everything will be all right.",
    "How did I get into the world? Why was I not asked about it and why was I not informed of the rules and regulations but just thrust into the ranks as if I had been bought by a peddling shanghaier of human beings? How did I get involved in this big enterprise called actuality? Why should I be involved? Isn't it a matter of choice? And if I am compelled to be involved, where is the manager—I have something to say about this. Is there no manager? To whom shall I make my complaint?",
    "It is so hard to believe because it is so hard to obey.",
    "Many of us pursue pleasure with such breathless haste that we hurry past it.",
    "The highest and most beautiful things in life are not to be heard about, nor read about, nor seen but, if one will, are to be lived.",
    "Deep within every human being there still lives the anxiety over the possibility of being alone in the world, forgotten by God, overlooked among the millions and millions in this enormous household. A person keeps this anxiety at a distance by looking at the many round about who are related to him as kin and friends, but the anxiety is still there.",
    "Truth always rests with the minority, and the minority is always stronger than the majority, because the minority is generally formed by those who really have an opinion, while the strength of a majority is illusory, formed by the gangs who have no opinion — and who, therefore, in the next instant (when it is evident that the minority is the stronger) assume its opinion… while truth again reverts to a new minority.",
    "There is nothing with which every man is so afraid as getting to know how enormously much he is capable of doing and becoming.",
    "How absurd men are! They never use the liberties they have, they demand those they do not have. They have freedom of thought, they demand freedom of speech.",
    "The self-assured believer is a greater sinner in the eyes of God than the troubled disbeliever.",
    "Anxiety may be compared with dizziness. He who's eye happens to look down into the yawning abyss becomes dizzy. But what is the reason for this? It is just as much in his own eyes as in the abyss...anxiety is the dizziness of freedom.",
    "...I will say that this is an adventure that every human being must go through - to learn  to be anxious...Whoever has learned to be anxious in the right way has learned the ultimate.",
    "If a human being did not have an eternal consciousness, if underlying everything there were only a wild, fermenting power that writhing in dark passions produced everything, be it significant or insignificant, if a vast, never appeased emptiness hid beneath everything, what would life be then but despair? (Fear and Trembling)",
    "Just as a mother admonishes her child who is about to attend a party, “Now, mind your manners and watch the other polite children and behave as they do”, so he, too, could live on and behave as he saw others behave. He would never do anything first and would never have any opinion unless he first knew that others had it…he would be more like a puppet character that very deceptively imitates all the human externalities…”",
    "One must always guard against contracting a life relationship by which one can become many. That is why even friendship is dangerous, marriage even more so. They do say marriage partners become one, but this is very obscure and mysterious talk. When you are one of several, then you have lost your freedom; you cannot send for your traveling boots whenever you wish, you cannot move aimlessly about in the world.",
    "The self which is the aim is not merely a personal self, but a social, a civic self. He has, then, himself as a task for an activity wherewith as this definite personality, he takes a hand in the affairs of life.",
    "He who is educated by anxiety is educated by possibility… When such a person, therefore, goes out from the school of possibility, and knows more thoroughly than a child knows the alphabet that he demands of life absolutely nothing, and that terror, perdition, annihilation, dwell next door to every man, and has learned the profitable lesson that every dread which alarms may the next instant become a fact, he will then interpret reality differently…”",
    "The formula that describes the state of the self when despair is completely rooted out is this: in relating itself to itself and in willing to be oneself, the self rests transparently in the power that established it. (Sickness Unto Death)",
    "By virtue of resignation, that rich young man should have given away everything, but if he had done so, then the knight of faith would have said to him: By virtue of the absurd, you will get every penny back again—believe it!",
    "…the finite tastes just as good to him as to one who never knew anything higher, because his remaining in finitude would have no trace of a timorous, anxious routine, and yet he has this security that makes him delight in it as if finitude were the surest thing of all…He resigned everything infinitely, and then he grasped everything again by virtue of the absurd. He is continually making the movement of infinity, but he does it with such precision and assurance that he continually gets finitude out of it, and no one ever suspects anything else.",
    "Without risk, there is no faith. Faith is precisely the contradiction between the infinite  passion of the individual’s inwardness and the objective uncertainty. If I am capable of  grasping God’s objectivity, I do not believe. If I  wish to preserve myself in faith I must  constantly be intent upon holding fast the objective uncertainty, so as to remain out  upon the deep, over seventy fathoms of water, still preserving my faith.",
    "Whether you are man or woman, rich or poor, dependent or free, happy or unhappy; whether you bore in your elevation the splendour of the crown or in humble obscurity only the toil and heat of the day; whether your name will be remembered for as long as the world lasts…or you are without a name and run namelessly with the numberless multitude…eternity asks you and every one of these millions of millions, just one thing: whether you have lived in despair or not…If then, if you have lived in despair, then whatever else you won or lost, for you everything is lost…"
    ]
}
