//
//  Nietzsche.swift
//  Daily quotes
//
//  Created by Abhijot Kaler on 09/09/20.
//  Copyright © 2020 KalerCorp. All rights reserved.
//

import Foundation

struct Nietzsche{
    var quotes: [String] = [
    "Man, the bravest of animals and the one most accustomed to suffering, does not repudiate suffering as such; he desires it, he even seeks it out, provided he is shown a meaning for it, a purpose of suffering. The meaninglessness of suffering, not suffering itself, was the curse that lay over mankind so far. (On the Genealogy of Morals)",
    "Nihilism appears at that point, not that the displeasure of existence has become greater than before but because one has come to mistrust any “meaning” in suffering, indeed in existence. …it now seems as if there is no meaning at all in existence, as if everything were in vain. (The Will to Power)",
    "The task of painting the picture of life, however often poets and philosophers may pose it, is nonetheless senseless: even under the hands of the greatest painter-thinkers all that has ever eventuated is pictures and miniatures out of one life, namely their own – and nothing else is even possible. (Human, all too Human)",
    "You want, if possible—and there is no more insane “if possible”—to abolish suffering. And we? It really seems that we would rather have it higher and worse than ever…The discipline of suffering, of great suffering—do you not know that only this discipline has created all enhancements of man so far? (Human, all too Human)",
    "A young shepherd I saw, writhing, gagging, in spasms, his face distorted, and a heavy black snake hung out of his mouth. Had I ever seen so much nausea and pale dread on one face?… My hand tore at the snake and tore in vain; it did not tear the snake out of his throat. Then it cried out of me: “Bite! Bite its head off! Bite!”.. The shepherd, however, bit as my cry counseled him; he bit with a good bite. Far away he spewed the head of the snake—and he jumped up. No longer shepherd, no longer human—one changed, radiant, laughing! Never yet on earth has a human being laughed as he laughed! O my brothers, I heard a laughter that was no human laughter. (Thus Spoke Zarathustra)",
    "I want to learn more and more to see as beautiful what is necessary in things; then I shall be one of those who make things beautiful. Amor fati: let that be my love henceforth! I do not want to wage war against what is ugly…And all in all and on the whole: some day I wish to be only a Yes-sayer. (The Gay Science)",
    "What, if some day or night a demon were to steal after you into your loneliest loneliness and say to you: “This life as you now live it and have lived it, you will have to live once more and innumerable times more; and there will be nothing new in it, but every pain and every joy and every thought and sigh and everything unutterably small and great in your life will have to return to you – all in the same succession and sequence…Would you throw yourself down and gnash your teeth and curse the demon who spoke thus? Or have you once experienced a tremendous moment when you would have answered him: “You are a god and never have I heard anything more divine.",
    "Furthermore, if an opinion makes us glad, it must be true; if its effect is good, it in itself must be good and true. Here one is attributing to the effect the predicate “gladdening,” “good,” in the sense of the useful, and providing the cause with the same predicate “good,” but now in the sense of the logically valid. The reversal of the proposition is: if a thing cannot prevail and maintain itself, it must be wrong; if an opinion tortures and agitates, it must be false. The free spirit, who comes to know all too well the error of this sort of deduction and has to suffer from its consequences, often succumbs to the temptation of making contrary deductions, which are in general naturally just as false: if a thing cannot prevail, it must be good; if an opinion troubles and disturbs, it must be true. (Human, All too Human)",
    "Most men tolerate life without grumbling too much and believe thus in the value of existence, but precisely because everyone wills himself alone and stands his ground alone, and does not step out of himself as do those exceptional men, everything extrapersonal escapes his notice entirely, or seems at the most a faint shadow. Thus the value of life for ordinary, everyday man is based only on his taking himself to be more important than the world. The great lack of fantasy from which he suffers keeps him from being able to empathize with other beings, and he therefore participates in their vicissitudes and suffering as little as possible. On the other hand, whoever would be truly able to participate in it would have to despair about the value of life; if he were able to grasp and feel mankind’s overall consciousness in himself, he would collapse with a curse against existence–for mankind, as whole, has no goals and consequently, considering the whole affair, man cannot find his comfort and support in it, but rather his despair.",
    "That which we now call the world is the result of a number of errors and fantasies, which came about gradually in the overall development of organic beings, fusing with one another, and now handed down to us as a collected treasure of our entire past–a treasure: for the value of our humanity rests upon it. (Human, All too Human)",
    "The man who would not belong in the mass needs only to cease being comfortable with himself; he should follow his conscience which shouts at him: “Be yourself! You are not really all that which you do, think, and desire now”. (Untimely Meditations III)",
    "When the great thinker despises human beings, he despises their laziness: for it is on account of their laziness that men seem like manufactured goods, unimportant, and unworthy. (Untimely Meditations III)",
    "For whoever proceeds on his own path meets nobody: this is the feature of one’s “own path.” No one comes to help him in his task: he must face everything quite alone — danger, bad luck, wickedness, foul weather. He goes his own way; and, as is only right, meets with bitterness and occasional irritation because he pursues this “own way”. (The Dawn)",
    "You refuse to be dissatisfied with yourselves or to suffer from yourselves, and this you call your moral tendency ! Very well ; another may perhaps call it your cowardice ! One thing, however, is certain, and that is that you will never take a trip round the world (and you yourselves are this world), and you will always remain in yourselves an accident and a clod on the face of the earth ! Do you fancy that we who hold different views from you are merely exposing ourselves out of pure folly to the journey through our own deserts, swamps, and glaciers, and that we are voluntarily choosing grief and disgust with ourselves…? (The Dawn)",
    "Ah, how little you know of the happiness of man, you comfortable and good-natured ones !-for happiness and misfortune are brother and sister, and twins, who grow tall together, or, as with you, remain small together! (The Gay Science)",
    "Creation—that is the great redemption from suffering, and life’s growing light. But that the creator may be, suffering is needed and much change. Indeed, there must be much bitter dying in your life, you creators. Thus are you advocates and justifiers of all impermanence. (Thus Spoke Zarathustra)",
    "Today, when suffering is always brought forward as the principal argument against existence, as the worst question mark, one does well to recall the ages in which the opposite opinion prevailed because men were unwilling to refrain from making suffer and saw in it an enchantment of the first order, a genuine seduction to life. Perhaps in those days—the delicate may be comforted by this thought—pain did not hurt as much as it does now. (On the Genealogy of Morals)",
    "All human life is sunk deep in untruth; the individual cannot pull it out of this well without growing profoundly annoyed with his entire past, without finding his present motives (like honor) senseless, and without opposing scorn and disdain to the passions that urge one on to the future and to the happiness in it. If this is true, is there only one way of thought left, with despair as a personal end and a philosophy of destruction as a theoretical end? I believe that a man’s temperament determines the aftereffect of knowledge; although the aftereffect described above is possible in some natures, I could just as well imagine a different one, which would give rise to a life much more simple, more free of affects than the present one. (Human, All Too Human)",
    "Even if we were mad enough to consider all our opinions as truth, we should nevertheless not wish them alone to exist. I cannot see why we should ask for an autocracy and omnipotence of truth : it is sufficient for me to know that it is a great power. Truth, however, must meet with opposition and be able to fight, and we must be able to rest from it at times in falsehood otherwise truth will grow tiresome, powerless, and insipid, and will render us equally so. (The Dawn)",
    "But this is an ancient, eternal story: what formerly happened with the Stoics still happens today, too, as soon as any philosophy begins to believe in itself. It always creates the world in its own image; it cannot do otherwise. Philosophy is this tyrannical drive itself, the most spiritual will to power, to the “creation of the world”. (Beyond Good and Evil)",
    "Over immense periods of time the intellect produced nothing but errors. A few of these proved to be useful and helped to preserve the species: those who hit upon or inherited these had better luck in their struggle for themselves and their progeny. (The Gay Science)",
    "It is now a good while since I first proposed for consideration the question whether convictions are not even more dangerous enemies to truth than lies. This time I desire to put the question definitely: is there any actual difference between a lie and a conviction? All the world believes that there is; but what is not believed by all the world! (The Antichrist)",
    "The truthful man, in the audacious and ultimate sense presupposed by the faith in science, thereby affirms another world than that of life, nature, and history; and insofar as he affirms this ‘other world,’ does this not mean that he has to deny its antithesis, this world, our world? … It is still a metaphysical faith that underlies our faith in science—and we men of knowledge of today, we godless men and anti-metaphysicians, we, too, still derive our flame from the fire ignited by a faith millennia old, the Christian faith, which was also Plato’s, that God is truth, that truth is divine.—But what if this belief is becoming more and more unbelievable, if nothing turns out to be divine any longer unless it be error, blindness, lies—if God himself turns out to be our longest lie? (On the Genealogy of Morals)",
    "How much truth does a spirit endure, how much truth does it dare? More and more that became for me the real measure of value. Error is not blindness, error is cowardice. Every attainment, every step forward in knowledge, follows from courage, from hardness against oneself, from cleanliness in relation to oneself. I do not refute ideals, I merely put on gloves before them. (Ecce Homo)",
    "History teaches us that that part of a people maintains itself best whose members generally share a vital public spirit, due to the similarity of their long-standing, incontrovertible principles, that is, of their common faith. In their case, good, sound custom strengthens them; they are taught to subordinate the individual, and their character is given solidity, at first innately and later through education. The danger in these strong communities, founded on similar, steadfast individual members, is an increasing, inherited stupidity, which follows all stability like a shadow. In such communities, spiritual progress depends on those individuals who are less bound, much less certain, and morally weaker; they are men who try new things, and many different things. (Human, All Too Human)",
    "All actions may be referred back to valuations, and all valuations are either one’s own or adopted, the latter being by far the more numerous. Why do we adopt them? Through fear, i.e. we think it more advisable to pretend that they are our own, and so well do we accustom ourselves to do so that it at last becomes second nature to us. A valuation of our own, which is the appreciation of a thing in accordance with the pleasure or displeasure it causes us and no one else, is something very rare indeed! (The Dawn)",
    "A young man can be most surely corrupted when he is taught to value the likeminded more highly than the differently minded. (The Dawn)",
    "Education proceeds in this manner throughout: it endeavors, by a series of enticements and advantages, to determine the individual to a certain mode of thinking and acting, which, when it has become habit, impulse and passion, rules in him and over him, in opposition to his ultimate advantage, but ” for the general good.” (The Gay Science)",
    "It is sufficient that his life is right in his own eyes, and maintains its right,-the life which calls to each of us : ” Be a man, and do not follow me-but yourself! Yourself!” Our life, also ought to maintain its right in our own eyes! We also are to grow and blossom out of ourselves, free and fearless, in innocent selfishness! (The Gay Science)",
    "But wherever I found the living, there I heard also the speech on obedience. Whatever lives, obeys. And this is the second point: he who cannot obey himself is commanded. That is the nature of the living. (Thus Spoke Zarathustra)",
    ]
}
