//
//  Schopenhauer.swift
//  Daily quotes
//
//  Created by Abhijot Kaler on 15/09/20.
//  Copyright © 2020 KalerCorp. All rights reserved.
//

import Foundation

struct Schopenhauer
{
    var quotes: [String] = [
    "What occupies all living things and keeps them in movement is striving for existence. With existence, however, when it is assured them, they have no idea what to do. Therefore, the second thing that sets them into movement is striving to be rid of the burden of existence, to render oneself insensible to it, to “kill time”, i.e., to escape boredom. (The World as Will and Representation)",
    "Accordingly, happiness lies always in the future, or else in the past, and the present may be compared to a small dark cloud driven by the wind over the sunny plain; in front of and behind the cloud everything is bright, only it itself always casts a shadow. (The World as Will and Representation)",
    "Life is deeply steeped in suffering, and cannot escape from it; our entrance into it takes place amid tears, at bottom its course is always tragic, and its end is even more so. (The World as Will and Representation)",
    "he wish is, in its nature, pain; the attainment soon begets satiety: the end was only apparent, possession takes away the charm; the wish, the need, presents itself under a new form; when it does not, there follows desolateness, emptiness, ennui, against which the conflict is just as painful as against want. (The World as Will and Representation)",
    "The striving we see everywhere hindered in many ways, everywhere in conflict, and therefore always under the form of suffering. Thus, if there is no final end of striving, there is no measure and end of suffering. (The World as Will and Representation)",
    "…it is easy to explain that man loves above everything else an existence which is full of want, misery, trouble, pain, anxiety, and then again full of boredom, and which, where it pondered over and considered purely objectively, he would of necessity abhor; and that he fears above everything else the end of this existence, which is nevertheless for him the one and only thing certain. Accordingly, we often seem miserable figure, deformed and bent with age, want, and disease, appeal to us from the bottom of his heart for help for the prolongation of existence whose end would necessarily appear as altogether desirable if it was an objective judgment that was the determining factor. (The World and Will and Representation)",
    "There is only one inborn error, and that is, that we exist in order to be happy. (The World as Will and Representation)",
    "The basis of all willing is need, lack, and hence pain, and by its very nature and origin it is therefore destined to pain. If, on the other hand, it lacks objects of willing, because it is at once deprived of them again by too easy a satisfaction, a fearful emptiness and boredom comes over it; in other words, its being and its existence itself becomes an intolerable burden for it. Hence life swings like pendulum to and fro between pain and boredom, and these two are in fact it has ultimate constituents. (The World as Will and Representation)",
    "Suffering is essential to life, and therefore does not flow in upon us from outside, but everyone carries around within himself its perennial source. (The World as Will and Representation)",
    "Life itself is a sea full of rocks and whirlpools that man avoids with the greatest caution and care, although he knows that, even when he succeeds with  all  his efforts and ingenuity in struggling through, at every step he comes nearer to the greatest, the total, the inevitable and irremediable shipwreck, indeed even steers right on to it, namely death. This is the final goal of the wearisome voyage, and is worse for him than all the rocks that he has avoided. (The World as Will and Representation)",
    "In the first place, no one is happy, but everyone throughout his life strives for an alleged happiness that is rarely attained, and even then only to disappoint him. As a rule, everyone ultimately reaches port with masts and rigging gone; but then it immaterial whether he was happy or unhappy in a life which consisted merely of a fleeting vanishing present and is now over and finished. (Parerga and Paralipomena)",
    "Behind need and want is to be found at once boredom, which attacks even the more intelligent animals. This is a consequence of the fact that life has no genuine intrinsic worth, but is kept in motion merely by want and illusion. But as soon as this comes to a standstill, the utter barrenness and emptiness of existence becomes apparent. (Parerga and Paralipomena)",
    "On the other hand, the present is accepted only for the time being, is set at naught, and looked upon merely as the path to the goal. Thus when at the end of their lives most men look back, they will find that they have lived throughout ad interim; they will be surprised to see that the very thing they allowed to slip by unappreciated and unenjoyed was just their life, precisely that in the expectation of which they lived. And so the course of a man’s life is, as a rule, such that, having been duped by hope, he dances into the arms of death. (Parerga and Paralipomena)",
    "We are like lambs playing in the field, while the butcher eyes them and selects first one and then another; for in our good days we do not know what calamity fate at this very moment has in store for us, sickness, persecution, impoverishment, mutilation, loss of sight, madness, death, and so on. (Parerga and Paralipomena)",
    "In early youth we sit before the impending course of our life like children at the theatre before the curtain is raised, who sit there in happy and excited expectation of the things that are to come. It is a blessing that we do not know what will actually come. For to the man who knows, the children may at times appear to be like innocent delinquents who are condemned not to death, it is true, but to life and have not yet grasped the purport of their sentence. Nevertheless everyone wants to reach old age and thus to a state of life, whereof it may be said: ‘It is bad today and every day it will get worse, until the world of all happens.(Parerga and Paralipomena)",
    "Life presents itself primarily as a task, namely that of gaining a livelihood…When this problem is solved, what has been gained is a burden, and there comes the second problem of how to dispose of what we have got in order to ward off boredom. Like a bird of prey on the watch, this evil pounces on every life that has been made secure. The first problem, therefore, is to acquire something and the second is to prevent it from making itself felt after it has been acquired, otherwise it is a burden. (Parerga and Paralipomena)",
    "…undoubtedly it is the knowledge of death, and therewith the consideration of the suffering and misery of life, that give the strongest impulse to philosophical reflection and metaphysical explanations of the world. (The World as Will and Representation)",
    "If our life were without end and free from pain, it would possibly not occur to anyone to ask why the world exists, and why it does so in precisely this way, but everything would be taken purely as a matter of course. (The World as Will and Representation)",
    "For if anything in the world is desirable, so desirable that even the dull and uneducated herd in its more reflective moments would value it more than silver and gold, it is that a ray of light should fall on the obscurity of our existence, and that we should obtain some information about this enigmatical life of ours, in which nothing is clear except its misery and vanity. (The World as Will and Representation)",
    "In endless space countless luminous spheres, round each of which some dozen smaller illuminated ones revolve, hot at the core and covered over with a hard cold crust; on this crust a mouldy film has produced living and knowing beings: this is empirical truth, the real, the world. Yet for a being who thinks, it is a precarious position to stand on one of those numberless spheres freely floating in boundless space, without knowing whence or whither, and to be only one of innumerable similar beings that throng, press, and toil, restlessly and rapidly arising and passing away in beginningless and endless time. (The World as Will and Representation)",
    "For the necessary starting point for all genuine philosophy is the deep feeling of the Socratic: 'This one thing I know, that I know nothing.' (The World as Will and Representation)",
    "With the exception of man, no being wonders at its own existence; but it is to them all so much a matter of course that they do not observe it. The wisdom of nature speaks of the peaceful glance of the brutes; for in them the will and the intellect are not yet so widely separated that they can be astonished at each other when they meet again. Only after the inner being of nature (the will to live in its objectification) has ascended, vigorous and cheerful, through the two series of unconscious existences, and then through the long and broad series of animals, does it attain at last to reflection for the first time on the entrance of reason, thus in man. Then it marvels at its own works, and asks itself what it itself is. Its wonder however is the more serious, as it here stands for the first time consciously in the presence of death, and besides the finiteness of all existence, the vanity of all effort forces itself more or less upon it. With this reflection and this wonder there arises therefore for man alone, the need for a metaphysic; he is accordingly an animal metaphysicum.",
    "I  turn to a general consideration of the other kind of metaphysics, that which has its authentication in itself, and is called  philosophy. I  remind the reader of its previously mentioned origin from a  wonder or astonishment  about the world and our own existence, since these obtrude themselves on the intellect as a riddle, whose solution then occupies mankind without intermission.",
    "…if accordingly we attempt to imagine an objective world without a knowing subject, then we become aware that what we are imagining at that moment is in truth the opposite of what we intended, namely nothing but just the process in the intellect of a knowing being who perceives an objective world, that is to say, precisely that which we had sought to exclude. For this perceptible and real world is obviously a phenomenon of the brain; and so in the assumption that the world as such might exist independently of all brains there lies a contradiction.",
    "…the being of an object in general belongs to the form of appearances, and is conditioned by the being of the subject in general, just as the object’s manner of appearance is conditioned by the subject’s forms of knowledge. Hence, if the thing in itself is to be assumed, it cannot be an object at all.",
    "…on the path of objective knowledge, thus starting from the representation, we shall never get beyond the representation, i.e. the phenomenon. We shall therefore remain at the outside of things: we shall never be able to penetrate into their inner nature, and investigate what they are in themselves, in other words, what they may be by themselves.",
    "Consequently, a way from within stands open to us to that real inner nature of things to which we cannot penetrate from without. It is, so to speak, a subterranean passage, a secret alliance, which, as if by treachery, places us all at once in the fortress that cannot be taken by attack from without.",
    "Everything presses and strives towards existence…Let any one consider this universal desire for life, let him see the infinite willingness, facility, and exuberance with which the will to live presses impetuously into existence under a million forms everywhere and at every moment…In such phenomena, then, it becomes visible that I am right in declaring that the will to live is that which cannot be further explained, but lies at the foundation of all explanation…",
    "We must therefore also apply the key for an understanding of the inner nature of things, a key that only the immediate knowledge of our own inner nature could give us, to these phenomena of the inorganic world, which are the most remote of all from us…For this word indicates that which is the being-in-itself of everything in the world, and is the sole kernel of every phenomenon.",
    "We will gradually become indifferent to what goes on in the minds of other people when we acquire a knowledge of the superficial nature of their thoughts, the narrowness of their views and of the number of their errors. Whoever attaches a lot of value to the opinions of others pays them too much honor.",
    ]
}
